language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - "sudo apt-get update"
  - "pip install django"
  - "pip install commonmark"
  - "pip install pillow"
  - "pip install beautifulsoup4"
  - "pip install feedparser"
  - "curl -L https://www.opscode.com/chef/install.sh | sudo bash"
  - "sudo -E chef-solo -j chef_installation.json -c chef_config.rb"
# command to run before the tests, setup chef.
before_script:
  - "python manage.py syncdb --noinput"
  - "python manage.py makemigrations"
  - "python manage.py migrate"
  - "python manage.py loaddata dummy"
# command to run tests, e.g. python setup.py test
script:
  - "python manage.py test"
  - "nosetests tests"